name = "JuliaUtils"
uuid = "fd6063e2-1dc5-4798-bfc3-ae02d434e5d9"
authors = ["Stefano Crotti"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
